meta_product_name: "Lilas Marchand"
meta_title: "Lilas Marchand - Fullstack developer junior on Ruby on Rails and Javascript"
meta_description: "I've created this website to let you discover my work and more about me. I hope you'll enjoy!"
meta_image: "PhotoCover.png" # should exist in `app/assets/images/`
